<a href="https://colab.research.google.com/github/juanchocor/Estudio/blob/main/Clase_python_ciencia_de_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy pandas matplotlib

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
eye_matrix = np.eye(5)
print(eye_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
array = np.array([10,20,30,40,50])
print(array[1])
print(array[-1])


20
50


In [ ]:
array_c = np.arange(1,10)
split_array = np.split(array,3)
print(array)
print(split_array)

ValueError: array split does not result in an equal division

In [ ]:
array_x = np.arange(10)
view_y = array_x[1:3]
print(array_x)
print(view_y)

[0 1 2 3 4 5 6 7 8 9]
[1 2]


Transformación de Arrays

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
transpose_matrix = matrix.T
print(matrix)
print(transpose_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
array = np.arange(1,13)
reshape_array = array.reshape(3,4)
print(array)
print(reshape_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
reversed_array = array[::-1]
print(array)
print(reversed_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[12 11 10  9  8  7  6  5  4  3  2  1]


In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
flatten_matrix = matrix.flatten()
print(matrix)
print(flatten_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]



**Análisis de Ventas Mensuales con NumPy: Transformaciones y Insights**

Usa la librería numpy para crear los siguientes arrays:
meses: un array con los nombres de los meses del año.
ventas_A, ventas_B, ventas_C: arrays que representan las ventas mensuales de tres productos diferentes.
Paso 2: Estadísticas Básicas

Calcula la media y la suma de ventas para los productos A, B y C usando las funciones de NumPy.
Imprime estos valores en el formato siguiente:
Media de ventas Producto A: <valor>
Suma de ventas Producto A: <valor>
Repite para los productos B y C.
Paso 3: Manipulación y Análisis de Datos

Total de ventas por mes: Suma las ventas de los tres productos para cada mes.
Promedio de ventas por producto: Calcula el promedio de ventas por producto.
Mes con mayor y menor ventas: Identifica qué mes tuvo el total de ventas más alto y cuál el más bajo usando las funciones np.argmax y np.argmin.
Paso 4: Operaciones Avanzadas con NumPy

Reshape y Transposición:

Crea una matriz 2D con las ventas de los tres productos y transforma su forma (reshape) a un array tridimensional con dimensiones (3, 4, 3).
Transpone la matriz de ventas para que las filas se conviertan en columnas.
Invertir arrays: Invierte las ventas de cada producto en orden de meses.
Aplanar la matriz: Convierte la matriz de ventas a un array unidimensional.
Paso 5: Análisis de Elementos Únicos

Utiliza np.unique para encontrar los elementos únicos en los datos de ventas y cuenta cuántas veces aparece cada uno.
Paso 6: Indexación y Slicing

Ventas del primer trimestre: Extrae las ventas de los tres primeros meses del año.
Indexación booleana: Selecciona los meses donde el total de ventas de los tres productos supere los 800.
Selección avanzada: Usa una lista de índices para seleccionar las ventas de los meses pares (o selecciona los meses a tu elección) y muestra esas ventas en una nueva matriz.

In [ ]:
meses = np.array(['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                  'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'])

ventas_A = np.array([150, 200, 250, 300, 220, 210, 180, 190, 230, 240, 280, 300])
ventas_B = np.array([180, 210, 230, 250, 270, 260, 240, 250, 270, 290, 310, 330])
ventas_C = np.array([200, 220, 240, 260, 280, 300, 320, 340, 360, 380, 400, 420])

In [ ]:
# Producto A
media_A = np.mean(ventas_A)
suma_A = np.sum(ventas_A)

# Producto B
media_B = np.mean(ventas_B)
suma_B = np.sum(ventas_B)

# Producto C
media_C = np.mean(ventas_C)
suma_C = np.sum(ventas_C)

# Mostrar resultados
print(f"Media de ventas Producto A: {media_A}")
print(f"Suma de ventas Producto A: {suma_A}\n")

print(f"Media de ventas Producto B: {media_B}")
print(f"Suma de ventas Producto B: {suma_B}\n")

print(f"Media de ventas Producto C: {media_C}")
print(f"Suma de ventas Producto C: {suma_C}")


Media de ventas Producto A: 229.16666666666666
Suma de ventas Producto A: 2750

Media de ventas Producto B: 257.5
Suma de ventas Producto B: 3090

Media de ventas Producto C: 310.0
Suma de ventas Producto C: 3720


In [ ]:
for i in range(len(meses)):
    print(f"{meses[i]}: {ventas_A[i]} unidades")


Enero: 150 unidades
Febrero: 200 unidades
Marzo: 250 unidades
Abril: 300 unidades
Mayo: 220 unidades
Junio: 210 unidades
Julio: 180 unidades
Agosto: 190 unidades
Septiembre: 230 unidades
Octubre: 240 unidades
Noviembre: 280 unidades
Diciembre: 300 unidades


Total de ventas por mes.


In [ ]:
total_mensual = ventas_A + ventas_B + ventas_C
print("Total de ventas por mes:\n", total_mensual)


Total de ventas por mes:
 [ 530  630  720  810  770  770  740  780  860  910  990 1050]


In [ ]:
print(f"Promedio Producto A: {np.mean(ventas_A)}")
print(f"Promedio Producto B: {np.mean(ventas_B)}")
print(f"Promedio Producto C: {np.mean(ventas_C)}")


Promedio Producto A: 229.16666666666666
Promedio Producto B: 257.5
Promedio Producto C: 310.0


In [ ]:
indice_max = np.argmax(total_mensual)
indice_min = np.argmin(total_mensual)

print(f"Mes con más ventas: {meses[indice_max]} ({total_mensual[indice_max]} unidades)")
print(f"Mes con menos ventas: {meses[indice_min]} ({total_mensual[indice_min]} unidades)")


Mes con más ventas: Diciembre (1050 unidades)
Mes con menos ventas: Enero (530 unidades)


In [ ]:
#Crear una matriz 2D con las ventas de los tres productos.
ventas_matriz = np.array([ventas_A, ventas_B, ventas_C])
print("Matriz de ventas (3 productos x 12 meses):\n", ventas_matriz)
print(ventas_matriz.shape)

Matriz de ventas (3 productos x 12 meses):
 [[150 200 250 300 220 210 180 190 230 240 280 300]
 [180 210 230 250 270 260 240 250 270 290 310 330]
 [200 220 240 260 280 300 320 340 360 380 400 420]]
(3, 12)


In [ ]:
ventas_3d = ventas_matriz.reshape(3, 4, 3)
print("Array 3D con shape (3, 4, 3):\n", ventas_3d)
print("Forma:", ventas_3d.shape)


Array 3D con shape (3, 4, 3):
 [[[150 200 250]
  [300 220 210]
  [180 190 230]
  [240 280 300]]

 [[180 210 230]
  [250 270 260]
  [240 250 270]
  [290 310 330]]

 [[200 220 240]
  [260 280 300]
  [320 340 360]
  [380 400 420]]]
Forma: (3, 4, 3)


In [ ]:
ventas_transpuesta = ventas_matriz.T
print("Matriz transpuesta (12 meses x 3 productos):\n", ventas_transpuesta)


Matriz transpuesta (12 meses x 3 productos):
 [[150 180 200]
 [200 210 220]
 [250 230 240]
 [300 250 260]
 [220 270 280]
 [210 260 300]
 [180 240 320]
 [190 250 340]
 [230 270 360]
 [240 290 380]
 [280 310 400]
 [300 330 420]]


In [ ]:
ventas_A_inv = ventas_A[::-1]
ventas_B_inv = ventas_B[::-1]
ventas_C_inv = ventas_C[::-1]

print("Ventas A invertidas:\n", ventas_A_inv)
print("Ventas B invertidas:\n", ventas_B_inv)
print("Ventas C invertidas:\n", ventas_C_inv)


Ventas A invertidas:
 [300 280 240 230 190 180 210 220 300 250 200 150]
Ventas B invertidas:
 [330 310 290 270 250 240 260 270 250 230 210 180]
Ventas C invertidas:
 [420 400 380 360 340 320 300 280 260 240 220 200]


In [ ]:
ventas_flat = ventas_matriz.flatten()
print("Array aplanado:\n", ventas_flat)
print("Forma:", ventas_flat.shape)


Array aplanado:
 [150 200 250 300 220 210 180 190 230 240 280 300 180 210 230 250 270 260
 240 250 270 290 310 330 200 220 240 260 280 300 320 340 360 380 400 420]
Forma: (36,)


In [ ]:
elementos_unicos, conteos = np.unique(ventas_flat, return_counts=True)

print("Valores únicos en las ventas:", elementos_unicos)
print("Frecuencia de cada valor:", conteos)


Valores únicos en las ventas: [150 180 190 200 210 220 230 240 250 260 270 280 290 300 310 320 330 340
 360 380 400 420]
Frecuencia de cada valor: [1 2 1 2 2 2 2 3 3 2 2 2 1 3 1 1 1 1 1 1 1 1]


In [ ]:
# Recordá: las posiciones 0, 1 y 2 son Ene, Feb y Mar
ventas_trim_A = ventas_A[:3]
ventas_trim_B = ventas_B[:3]
ventas_trim_C = ventas_C[:3]

print("Ventas Producto A - Primer Trimestre:", ventas_trim_A)
print("Ventas Producto B - Primer Trimestre:", ventas_trim_B)
print("Ventas Producto C - Primer Trimestre:", ventas_trim_C)


Ventas Producto A - Primer Trimestre: [150 200 250]
Ventas Producto B - Primer Trimestre: [180 210 230]
Ventas Producto C - Primer Trimestre: [200 220 240]


In [ ]:
# Crear máscara booleana
mascara = total_mensual > 800

# Filtrar meses y totales
meses_mayores_800 = meses[mascara]
ventas_mayores_800 = total_mensual[mascara]

print("Meses con más de 800 ventas totales:", meses_mayores_800)
print("Ventas totales en esos meses:", ventas_mayores_800)


Meses con más de 800 ventas totales: ['Abril' 'Septiembre' 'Octubre' 'Noviembre' 'Diciembre']
Ventas totales en esos meses: [ 810  860  910  990 1050]


In [ ]:
# Índices de meses pares: 1, 3, 5, 7, 9, 11
indices_pares = [1, 3, 5, 7, 9, 11]

ventas_A_pares = ventas_A[indices_pares]
ventas_B_pares = ventas_B[indices_pares]
ventas_C_pares = ventas_C[indices_pares]
meses_pares = meses[indices_pares]

print("Meses pares:", meses_pares)
print("Ventas A en meses pares:", ventas_A_pares)
print("Ventas B en meses pares:", ventas_B_pares)
print("Ventas C en meses pares:", ventas_C_pares)


Meses pares: ['Febrero' 'Abril' 'Junio' 'Agosto' 'Octubre' 'Diciembre']
Ventas A en meses pares: [200 300 210 190 240 300]
Ventas B en meses pares: [210 250 260 250 290 330]
Ventas C en meses pares: [220 260 300 340 380 420]


Calculos Matriciales

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

#suma
suma = A + B
print(suma)

[[ 6  8]
 [10 12]]


In [ ]:
#Multiplicación
product = np.dot(A,B)
print(product)

[[19 22]
 [43 50]]


In [ ]:
A = np.array([[1,2],[3,4]])
det_A = np.linalg.det(A)
inv_A = np.linalg.inv(A)
print(A)
print(inv_A)
print(det_A)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004


In [ ]:
#Resolver Ax = b
A = np.array([[2,1,-2],[3,0,1],[1,1,-1]])
b = np.array([8,-3,-2])
x = np.linalg.solve(A,b)
print(x)

[  1.75 -12.    -8.25]


# Pandas: Dataset

In [5]:
import pandas as pd

path = '/Online_Retail.csv'
# Attempt to read the CSV with 'latin-1' encoding
retail_data = pd.read_csv(path, encoding='latin-1')

#leer como excel
#data_axcel = pd.read_excel(path)

#Leer como Json
#data_json = pd.read_json(paht)

#print(type(retail_data))
print(retail_data)

       InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6   
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4   
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3   

          InvoiceDate  UnitPrice  CustomerID         Country  
0        12/

##Estructuras y funciones

In [7]:
#Conocer los nombres de las columnas
columns_names = retail_data.columns
print(columns_names)

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')


In [10]:
num_rows, num_columns = retail_data.shape
print('Numero de filas', num_rows)
print('Numero de columnas', num_columns)

Numero de filas 541909
Numero de columnas 8


In [11]:
daily_sales = retail_data['Quantity']
print(daily_sales)

0          6
1          6
2          8
3          6
4          6
          ..
541904    12
541905     6
541906     4
541907     4
541908     3
Name: Quantity, Length: 541909, dtype: int64


In [12]:
summary = retail_data.describe()
print(summary)

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000


##Obtener la media

In [18]:
mean_value = daily_sales.mean()
print('La media es', mean_value)

La media es 9.55224954743324


##Obtener Mediana

In [19]:
median_value = daily_sales.median()
print('La mediana es', mean_value)

La mediana es 9.55224954743324


In [20]:
#Sumar
sum_value = daily_sales.sum()
print('La suma total es', mean_value)


La suma total es 9.55224954743324


In [21]:
count_values =  daily_sales.count()
print('La cantidad de valores es', count_values)

La cantidad de valores es 541909


In [22]:
#Metodo head
retail_data.head()


InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1    536365     71053                  WHITE METAL LANTERN         6   
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   

    InvoiceDate  UnitPrice  CustomerID         Country  
0  12/1/10 8:26       2.55     17850.0  United Kingdom  
1  12/1/10 8:26       3.39     17850.0  United Kingdom  
2  12/1/10 8:26       2.75     17850.0  United Kingdom  
3  12/1/10 8:26       3.39     17850.0  United Kingdom  
4  12/1/10 8:26       3.39     17850.0  United Kingdom