<a href="https://colab.research.google.com/github/juanchocor/Estudio/blob/main/Clase_python_ciencia_de_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy pandas matplotlib

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
eye_matrix = np.eye(5)
print(eye_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [4]:
array = np.array([10,20,30,40,50])
print(array[1])
print(array[-1])


20
50


In [5]:
array_c = np.arange(1,10)
split_array = np.split(array,3)
print(array)
print(split_array)

ValueError: array split does not result in an equal division

In [6]:
array_x = np.arange(10)
view_y = array_x[1:3]
print(array_x)
print(view_y)

[0 1 2 3 4 5 6 7 8 9]
[1 2]


Transformación de Arrays

In [7]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
transpose_matrix = matrix.T
print(matrix)
print(transpose_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [8]:
array = np.arange(1,13)
reshape_array = array.reshape(3,4)
print(array)
print(reshape_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
reversed_array = array[::-1]
print(array)
print(reversed_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[12 11 10  9  8  7  6  5  4  3  2  1]


In [10]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
flatten_matrix = matrix.flatten()
print(matrix)
print(flatten_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]



**Análisis de Ventas Mensuales con NumPy: Transformaciones y Insights**

Usa la librería numpy para crear los siguientes arrays:
meses: un array con los nombres de los meses del año.
ventas_A, ventas_B, ventas_C: arrays que representan las ventas mensuales de tres productos diferentes.
Paso 2: Estadísticas Básicas

Calcula la media y la suma de ventas para los productos A, B y C usando las funciones de NumPy.
Imprime estos valores en el formato siguiente:
Media de ventas Producto A: <valor>
Suma de ventas Producto A: <valor>
Repite para los productos B y C.
Paso 3: Manipulación y Análisis de Datos

Total de ventas por mes: Suma las ventas de los tres productos para cada mes.
Promedio de ventas por producto: Calcula el promedio de ventas por producto.
Mes con mayor y menor ventas: Identifica qué mes tuvo el total de ventas más alto y cuál el más bajo usando las funciones np.argmax y np.argmin.
Paso 4: Operaciones Avanzadas con NumPy

Reshape y Transposición:

Crea una matriz 2D con las ventas de los tres productos y transforma su forma (reshape) a un array tridimensional con dimensiones (3, 4, 3).
Transpone la matriz de ventas para que las filas se conviertan en columnas.
Invertir arrays: Invierte las ventas de cada producto en orden de meses.
Aplanar la matriz: Convierte la matriz de ventas a un array unidimensional.
Paso 5: Análisis de Elementos Únicos

Utiliza np.unique para encontrar los elementos únicos en los datos de ventas y cuenta cuántas veces aparece cada uno.
Paso 6: Indexación y Slicing

Ventas del primer trimestre: Extrae las ventas de los tres primeros meses del año.
Indexación booleana: Selecciona los meses donde el total de ventas de los tres productos supere los 800.
Selección avanzada: Usa una lista de índices para seleccionar las ventas de los meses pares (o selecciona los meses a tu elección) y muestra esas ventas en una nueva matriz.

In [11]:
meses = np.array(['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                  'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'])

ventas_A = np.array([150, 200, 250, 300, 220, 210, 180, 190, 230, 240, 280, 300])
ventas_B = np.array([180, 210, 230, 250, 270, 260, 240, 250, 270, 290, 310, 330])
ventas_C = np.array([200, 220, 240, 260, 280, 300, 320, 340, 360, 380, 400, 420])

In [12]:
# Producto A
media_A = np.mean(ventas_A)
suma_A = np.sum(ventas_A)

# Producto B
media_B = np.mean(ventas_B)
suma_B = np.sum(ventas_B)

# Producto C
media_C = np.mean(ventas_C)
suma_C = np.sum(ventas_C)

# Mostrar resultados
print(f"Media de ventas Producto A: {media_A}")
print(f"Suma de ventas Producto A: {suma_A}\n")

print(f"Media de ventas Producto B: {media_B}")
print(f"Suma de ventas Producto B: {suma_B}\n")

print(f"Media de ventas Producto C: {media_C}")
print(f"Suma de ventas Producto C: {suma_C}")


Media de ventas Producto A: 229.16666666666666
Suma de ventas Producto A: 2750

Media de ventas Producto B: 257.5
Suma de ventas Producto B: 3090

Media de ventas Producto C: 310.0
Suma de ventas Producto C: 3720


In [13]:
for i in range(len(meses)):
    print(f"{meses[i]}: {ventas_A[i]} unidades")


Enero: 150 unidades
Febrero: 200 unidades
Marzo: 250 unidades
Abril: 300 unidades
Mayo: 220 unidades
Junio: 210 unidades
Julio: 180 unidades
Agosto: 190 unidades
Septiembre: 230 unidades
Octubre: 240 unidades
Noviembre: 280 unidades
Diciembre: 300 unidades


Total de ventas por mes.


In [14]:
total_mensual = ventas_A + ventas_B + ventas_C
print("Total de ventas por mes:\n", total_mensual)


Total de ventas por mes:
 [ 530  630  720  810  770  770  740  780  860  910  990 1050]


In [15]:
print(f"Promedio Producto A: {np.mean(ventas_A)}")
print(f"Promedio Producto B: {np.mean(ventas_B)}")
print(f"Promedio Producto C: {np.mean(ventas_C)}")


Promedio Producto A: 229.16666666666666
Promedio Producto B: 257.5
Promedio Producto C: 310.0


In [16]:
indice_max = np.argmax(total_mensual)
indice_min = np.argmin(total_mensual)

print(f"Mes con más ventas: {meses[indice_max]} ({total_mensual[indice_max]} unidades)")
print(f"Mes con menos ventas: {meses[indice_min]} ({total_mensual[indice_min]} unidades)")


Mes con más ventas: Diciembre (1050 unidades)
Mes con menos ventas: Enero (530 unidades)


In [17]:
#Crear una matriz 2D con las ventas de los tres productos.
ventas_matriz = np.array([ventas_A, ventas_B, ventas_C])
print("Matriz de ventas (3 productos x 12 meses):\n", ventas_matriz)
print(ventas_matriz.shape)

Matriz de ventas (3 productos x 12 meses):
 [[150 200 250 300 220 210 180 190 230 240 280 300]
 [180 210 230 250 270 260 240 250 270 290 310 330]
 [200 220 240 260 280 300 320 340 360 380 400 420]]
(3, 12)


In [ ]:
ventas_3d = ventas_matriz.reshape(3, 4, 3)
print("Array 3D con shape (3, 4, 3):\n", ventas_3d)
print("Forma:", ventas_3d.shape)


In [ ]:
ventas_transpuesta = ventas_matriz.T
print("Matriz transpuesta (12 meses x 3 productos):\n", ventas_transpuesta)


In [ ]:
ventas_A_inv = ventas_A[::-1]
ventas_B_inv = ventas_B[::-1]
ventas_C_inv = ventas_C[::-1]

print("Ventas A invertidas:\n", ventas_A_inv)
print("Ventas B invertidas:\n", ventas_B_inv)
print("Ventas C invertidas:\n", ventas_C_inv)


In [ ]:
ventas_flat = ventas_matriz.flatten()
print("Array aplanado:\n", ventas_flat)
print("Forma:", ventas_flat.shape)


In [ ]:
elementos_unicos, conteos = np.unique(ventas_flat, return_counts=True)

print("Valores únicos en las ventas:", elementos_unicos)
print("Frecuencia de cada valor:", conteos)


In [ ]:
# Recordá: las posiciones 0, 1 y 2 son Ene, Feb y Mar
ventas_trim_A = ventas_A[:3]
ventas_trim_B = ventas_B[:3]
ventas_trim_C = ventas_C[:3]

print("Ventas Producto A - Primer Trimestre:", ventas_trim_A)
print("Ventas Producto B - Primer Trimestre:", ventas_trim_B)
print("Ventas Producto C - Primer Trimestre:", ventas_trim_C)


In [ ]:
# Crear máscara booleana
mascara = total_mensual > 800

# Filtrar meses y totales
meses_mayores_800 = meses[mascara]
ventas_mayores_800 = total_mensual[mascara]

print("Meses con más de 800 ventas totales:", meses_mayores_800)
print("Ventas totales en esos meses:", ventas_mayores_800)


In [ ]:
# Índices de meses pares: 1, 3, 5, 7, 9, 11
indices_pares = [1, 3, 5, 7, 9, 11]

ventas_A_pares = ventas_A[indices_pares]
ventas_B_pares = ventas_B[indices_pares]
ventas_C_pares = ventas_C[indices_pares]
meses_pares = meses[indices_pares]

print("Meses pares:", meses_pares)
print("Ventas A en meses pares:", ventas_A_pares)
print("Ventas B en meses pares:", ventas_B_pares)
print("Ventas C en meses pares:", ventas_C_pares)


Calculos Matriciales

In [18]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

#suma
suma = A + B
print(suma)

[[ 6  8]
 [10 12]]


In [19]:
#Multiplicación
product = np.dot(A,B)
print(product)

[[19 22]
 [43 50]]


In [ ]:
A = np.array([[1,2],[3,4]])
det_A = np.linalg.det(A)
inv_A = np.linalg.inv(A)
print(A)
print(inv_A)
print(det_A)

In [ ]:
#Resolver Ax = b
A = np.array([[2,1,-2],[3,0,1],[1,1,-1]])
b = np.array([8,-3,-2])
x = np.linalg.solve(A,b)
print(x)

# Pandas: Dataset

In [21]:
import pandas as pd

path = '/Online_Retail.csv'
# Attempt to read the CSV with 'latin-1' encoding
retail_data = pd.read_csv(path, encoding='latin-1')

#leer como excel
#data_axcel = pd.read_excel(path)

#Leer como Json
#data_json = pd.read_json(paht)

#print(type(retail_data))
print(retail_data)

       InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6   
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4   
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3   

          InvoiceDate  UnitPrice  CustomerID         Country  
0        12/

##Estructuras y funciones

In [22]:
#Conocer los nombres de las columnas
columns_names = retail_data.columns
print(columns_names)

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')


In [23]:
num_rows, num_columns = retail_data.shape
print('Numero de filas', num_rows)
print('Numero de columnas', num_columns)

Numero de filas 541909
Numero de columnas 8


In [24]:
daily_sales = retail_data['Quantity']
print(daily_sales)

0          6
1          6
2          8
3          6
4          6
          ..
541904    12
541905     6
541906     4
541907     4
541908     3
Name: Quantity, Length: 541909, dtype: int64


In [25]:
summary = retail_data.describe()
print(summary)

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000


##Obtener la media

In [26]:
mean_value = daily_sales.mean()
print('La media es', mean_value)

La media es 9.55224954743324


##Obtener Mediana

In [27]:
median_value = daily_sales.median()
print('La mediana es', mean_value)

La mediana es 9.55224954743324


In [28]:
#Sumar
sum_value = daily_sales.sum()
print('La suma total es', mean_value)


La suma total es 9.55224954743324


In [29]:
count_values =  daily_sales.count()
print('La cantidad de valores es', count_values)

La cantidad de valores es 541909


In [30]:
#Metodo head
retail_data.head()


InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1    536365     71053                  WHITE METAL LANTERN         6   
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   

    InvoiceDate  UnitPrice  CustomerID         Country  
0  12/1/10 8:26       2.55     17850.0  United Kingdom  
1  12/1/10 8:26       3.39     17850.0  United Kingdom  
2  12/1/10 8:26       2.75     17850.0  United Kingdom  
3  12/1/10 8:26       3.39     17850.0  United Kingdom  
4  12/1/10 8:26       3.39     17850.0  United Kingdom

##Manipulación de columnas


In [35]:
#Crear nueva columnas
# Usar la variable 'path' que contiene la ruta correcta al archivo
df = pd.read_csv(path, encoding='latin-1')
df['TotalPrice'] = df['Quantity'] * df['UnitPrice']
print(df.head())

  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1    536365     71053                  WHITE METAL LANTERN         6   
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   

    InvoiceDate  UnitPrice  CustomerID         Country  TotalPrice  
0  12/1/10 8:26       2.55     17850.0  United Kingdom       15.30  
1  12/1/10 8:26       3.39     17850.0  United Kingdom       20.34  
2  12/1/10 8:26       2.75     17850.0  United Kingdom       22.00  
3  12/1/10 8:26       3.39     17850.0  United Kingdom       20.34  
4  12/1/10 8:26       3.39     17850.0  United Kingdom       20.34  


In [38]:
df['HighValue'] = df['TotalPrice'] > 16
print(df['HighValue'].head(10))

0    False
1     True
2     True
3     True
4     True
5    False
6     True
7    False
8    False
9     True
Name: HighValue, dtype: bool


In [39]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   InvoiceNo    541909 non-null  object 
 1   StockCode    541909 non-null  object 
 2   Description  540455 non-null  object 
 3   Quantity     541909 non-null  int64  
 4   InvoiceDate  541909 non-null  object 
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object 
 8   TotalPrice   541909 non-null  float64
 9   HighValue    541909 non-null  bool   
dtypes: bool(1), float64(3), int64(1), object(5)
memory usage: 37.7+ MB
None


In [40]:
#vamos a cambiar la columnas de 'InvoiceDate' a tipo fecha ya que está como una objeto.
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
print(df.info())

/tmp/ipython-input-40-455805193.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype         
---  ------       --------------   -----         
 0   InvoiceNo    541909 non-null  object        
 1   StockCode    541909 non-null  object        
 2   Description  540455 non-null  object        
 3   Quantity     541909 non-null  int64         
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64       
 6   CustomerID   406829 non-null  float64       
 7   Country      541909 non-null  object        
 8   TotalPrice   541909 non-null  float64       
 9   HighValue    541909 non-null  bool          
dtypes: bool(1), datetime64[ns](1), float64(3), int64(1), object(4)
memory usage: 37.7+ MB
None


In [42]:
#aqui aplicamos un 10 % de descuento usando una funcion lambda
df['DiscountedPrice'] = df['UnitPrice'].apply(lambda x: x * 0.9)
print(df.head(3))

  InvoiceNo StockCode                         Description  Quantity  \
0    536365    85123A  WHITE HANGING HEART T-LIGHT HOLDER         6   
1    536365     71053                 WHITE METAL LANTERN         6   
2    536365    84406B      CREAM CUPID HEARTS COAT HANGER         8   

          InvoiceDate  UnitPrice  CustomerID         Country  TotalPrice  \
0 2010-12-01 08:26:00       2.55     17850.0  United Kingdom       15.30   
1 2010-12-01 08:26:00       3.39     17850.0  United Kingdom       20.34   
2 2010-12-01 08:26:00       2.75     17850.0  United Kingdom       22.00   

   HighValue  DiscountedPrice  
0      False            2.295  
1       True            3.051  
2       True            2.475  


In [45]:
def categorize_price(price):
  if price < 50:
    return 'High'
  elif price < 20:
    return 'Medium'
  else:
    return 'low'

df['PriceCategory'] = df['UnitPrice'].apply(categorize_price)
print(df.head(10))

  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1    536365     71053                  WHITE METAL LANTERN         6   
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
5    536365     22752         SET 7 BABUSHKA NESTING BOXES         2   
6    536365     21730    GLASS STAR FROSTED T-LIGHT HOLDER         6   
7    536366     22633               HAND WARMER UNION JACK         6   
8    536366     22632            HAND WARMER RED POLKA DOT         6   
9    536367     84879        ASSORTED COLOUR BIRD ORNAMENT        32   

          InvoiceDate  UnitPrice  CustomerID         Country  TotalPrice  \
0 2010-12-01 08:26:00       2.55     17850.0  United Kingdom       15.30   
1 2010-12-01 08:26:00       3.39     17850.0  United Ki

##Groupby

In [46]:
country_count = df['Country'].value_counts()
print(country_count)

Country
United Kingdom          495478
Germany                   9495
France                    8557
EIRE                      8196
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               2002
Portugal                  1519
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Unspecified                446
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
Israel                     297
USA                        291
Hong Kong                  288
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         58


In [47]:
country_group = df.groupby('Country')['Quantity'].sum()
print(country_group)

Country
Australia                 83653
Austria                    4827
Bahrain                     260
Belgium                   23152
Brazil                      356
Canada                     2763
Channel Islands            9479
Cyprus                     6317
Czech Republic              592
Denmark                    8188
EIRE                     142637
European Community          497
Finland                   10666
France                   110480
Germany                  117448
Greece                     1556
Hong Kong                  4769
Iceland                    2458
Israel                     4353
Italy                      7999
Japan                     25218
Lebanon                     386
Lithuania                   652
Malta                       944
Netherlands              200128
Norway                    19247
Poland                     3653
Portugal                  16180
RSA                         352
Saudi Arabia                 75
Singapore                  5234


In [48]:
country_stats = df.groupby('Country')['UnitPrice'].agg(['mean','sum'])
print(country_stats)

                            mean          sum
Country                                      
Australia               3.220612     4054.750
Austria                 4.243192     1701.520
Bahrain                 4.556316       86.570
Belgium                 3.644335     7540.130
Brazil                  4.456250      142.600
Canada                  6.030331      910.580
Channel Islands         4.932124     3738.550
Cyprus                  6.302363     3920.070
Czech Republic          2.938333       88.150
Denmark                 3.256941     1266.950
EIRE                    5.911077    48447.190
European Community      4.820492      294.050
Finland                 5.448705     3786.850
France                  5.028864    43031.990
Germany                 3.966930    37666.000
Greece                  4.885548      713.290
Hong Kong              42.505208    12241.500
Iceland                 2.644011      481.210
Israel                  3.633131     1079.040
Italy                   4.831121  

In [49]:
country_stock_group = df.groupby(['Country','StockCode'])['Quantity'].sum()
print(country_stock_group)

Country      StockCode
Australia    15036        600
             15056BL        3
             16161P       400
             16169E        25
             20665          6
                         ... 
Unspecified  85180A         2
             85180B         1
             85212         12
             85213         12
             85227         10
Name: Quantity, Length: 19839, dtype: int64


In [50]:
#quiero obtener el revenue de cada pais
def total_revenue(group):
  return(group['Quantity'] * group['UnitPrice']).sum()

country_per_country = df.groupby('Country').apply(total_revenue)
print(country_per_country)

Country
Australia                137077.270
Austria                   10154.320
Bahrain                     548.400
Belgium                   40910.960
Brazil                     1143.600
Canada                     3666.380
Channel Islands           20086.290
Cyprus                    12946.290
Czech Republic              707.720
Denmark                   18768.140
EIRE                     263276.820
European Community         1291.750
Finland                   22326.740
France                   197403.900
Germany                  221698.210
Greece                     4710.520
Hong Kong                 10117.040
Iceland                    4310.000
Israel                     7907.820
Italy                     16890.510
Japan                     35340.620
Lebanon                    1693.880
Lithuania                  1661.060
Malta                      2505.470
Netherlands              284661.540
Norway                    35163.460
Poland                     7213.140
Portugal            

/tmp/ipython-input-50-1180459355.py:5: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  country_per_country = df.groupby('Country').apply(total_revenue)


In [52]:
top_3 = country_per_country.sort_values(ascending=False).head(3)
bottom_3 = country_per_country.sort_values().head(3)

print("Top 3 países:\n", top_3)
print("Bottom 3 países:\n", bottom_3)

Top 3 países:
 Country
United Kingdom    8187806.364
Netherlands        284661.540
EIRE               263276.820
dtype: float64
Bottom 3 países:
 Country
Saudi Arabia      131.17
Bahrain           548.40
Czech Republic    707.72
dtype: float64
